name: Assume

on:
  push:
    paths:
      - '.github/workflows/assume.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
    env:
      name: dev
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ env.name }}-cooperation-execution
          role-duration-seconds: 1200
          role-session-name: assume
      - name: test
#        run: aws s3 sync s3://dev-sample-static-page-storage ./
        run: echo ${{ env }}
